---

joomla_db: "joomla_db"
joomla_user: "joomla_user"
joomla_password: "joomla_password"
joomla_config: "/var/www/html/joomla/installation/configuration.php"
joomla_apache_conf: "/etc/apache2/sites-available/joomla.conf"
joomla_url: "https://downloads.joomla.org/cms/joomla3/3-10-12/Joomla_3-10-12-Stable-Full_Package.zip"
